version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - toddy-db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - "4004:4004"
    volumes:
      - .:/usr/src/app

volumes:
  toddy-db:
